notownteritorry: "&eFactions &8| &fNu poti sa folosesti &eTNT Wand &fpe alte claim-uri!"
reload: "&aConfig reloaded!"
help:
  - "&e&o&nTNTWands"
  - "&8- &f/tntwands reload"
  - "&8- &f/tntwands give <player> [uses]"
  - "&e&lTIP: &7&oLeave uses empty for infinite uses."
unknowncommand: "&eFactions &8| &fComanda necunoscuta! Scrie &e/tntwands &fpentru a vedea lista de comenzi!"
infinite: "infinite"
giveusage: "&eUsage: &f&o/tntwands give <player> [uses]"
givetarget: "&eFactions &8| &fAi primit un &eTNT Wand &fcu &e%uses% &ffolosiri!"
givesender: "&eFactions &8| &fI-ai dat jucatorului &e%target% &fun &eTNT Wand &fcu &e%uses% &ffolosiri!"
notnt: "&eFactions &8| &fAcest chest nu contine TNT!"
toomuchtnt: "&eFactions &8| &fNu ai destul loc in banca de TNT a factiunii!"
addedtnt: "&eFactions &8| &fAi adaugat %tnt% in banca factiunii %faction%."
wand:
  material: "STICK"
  name: "&4&l&nTNT&r &c&l&nWAND"
  lore:
    - "&8Uses: %uses%"
    - "&8Owner: %owner%"
    - "&f"
    - "&e&oYou can use this wand in your own territory"
    - "&e&oto store the TNT inside the chest that you click!"